### ISSUE TITLE
ShmQueue: read_next_block_id(...) Shuffles Blocks?

### ISSUE THREAD

**Issue by CraigMiloRogers** [usc-isi-i2/paralyzer#8]
I think the polling strategy in read_next_block_id(...) and next_writeable_block_id(...) will cause get(...) to skip blocks due to a race condition. In other words, get(...) can read the chunk with chunk_id == total_chunks before it sees all of the chunks.

**Comment by CraigMiloRogers** [comment]
If true, this explains the unpicking error.

**Comment by GreatYYX** [comment]
This sounds possible. It doesn't have block-level read lock. The locks in ShmQueue are 1) producer lock 2) consumer lock 3) block-level write lock. Only one producer or consumer can work at one time.

**Comment by GreatYYX** [comment]
This issue is caused by https://github.com/usc-isi-i2/pyrallel/blob/4cb3581ac82a9a8409efd6d4c70be4e251f64990/pyrallel/queue.py#L237

The fix can be very simple: it only needs to create a list locally and unpickle and return if all chunks in the list arrives.

**Comment by CraigMiloRogers** [comment]
I've posted a pull request with some changes that fix problems, including this one.

**Comment by CraigMiloRogers** [comment]
Fixed on the dev queue.
