### ISSUE TITLE
ParallelProcessor Doesn't Use ShmQueue

### ISSUE THREAD

**Issue by CraigMiloRogers** [usc-isi-i2/paralyzer#9]
ParallelProcessor doesn't use ShmQueue.

**Comment by CraigMiloRogers** [comment]
I've created a version that optionally uses ShmQueue. I will check it into my forked repo.

**Comment by GreatYYX** [comment]
No it doesn't. Right now ShmQueue is a standalone component. I will make the I/O queue configurable in ParallelProcessor and MapReduce once ShmQueue is stable enough.

**Comment by CraigMiloRogers** [comment]
Fixed on the dev branch
